#!/usr/bin/env bash
# Configure Nginx

apt update
apt -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart
