#!/usr/bin/env bash
# Configure Nginx

apt update
apt install -y nginx

echo "Holberton School" > /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
	listen 80 default_server;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

	error_page 404 /404.html;
}" > /etc/nginx/sites-available/default

service nginx reload
